---
title: "High_Value and Non_High_Value Accounts"
author: "Eric Curiel"
date: "6/30/2017"
output: html_notebook
---

The data is a data frame of accounts with features about each account in the associated coloumns. The "HighValue"" accounts group has 170 entries for each of the three features we are interested in. The "Non_HighValue" group has 412 entries. We will assume that each feature (number of employees- "Employe_count"", year business was- "Founded", growth over the last six moths- "Employee_growth_6Months") comes from a normal distribution given the large sample size for each. 

The Hypothesis Test we will do is a 2-tailed test to determine if the true mean for, say, "Employee_count" from the HighValue group is equal to the true mean of Employee_count from Non_HighValue group. The alternative Hypothesis is that these means are not equal and thus their is a statistically significant difference in the means for these two groups. I will perform the test for each the three features previously mentioned. Although we will assume a normal distribution, I will perform a variance test to check for homoscedasticity. The alpha level for my tests will be .05.

```{r setup, include=FALSE}
crmdata_HV<-read.csv('~/Desktop/Udacity/crmdata_R_HighValue.csv')
crmdata_non_HV<-read.csv('~/Desktop/Udacity/crmdata-non_HighValue.csv')

str(crmdata_HV)
str(crmdata_non_HV)

#Var test to see if data set passes assumption of equal varienaces for t-test. Ho=variance is equal in both groups. Ha= variance is not equal in both groups Alpha= .05
var.test(crmdata_non_HV$Employee_count,crmdata_HV$Employee_count)
var.test(crmdata_non_HV$Founded,crmdata_HV$Founded)
var.test(crmdata_non_HV$Employee_growth_6Months,crmdata_HV$Employee_growth_6Months)
#All vectors fail var.test meaning the evidence strongly suggests "true ratio of varince not equal to 1," given the p-value is < 2.2e-16. Thus we will have to make adjustment for T-test.

#Next we perform a two sample t-test to see compare true mean of each feature in HighValue to non_HighValue. mu is equal to 0 since we are testing against the null hypothesis-that their is no difference in the true means of the two groups. Ho= true mean of the feature in HighValue group is equal to the true mean for the feature in non_HighValue group. Ha= true mean is not equal in the two groups(two-tailed test) alpha = .05

t.test( crmdata_HV$Employee_count,crmdata_non_HV$Employee_count, mu = 0, var.equal=FALSE)
t.test( crmdata_non_HV$Founded,crmdata_HV$Founded, mu = 0, var.equal=FALSE) 
t.test( crmdata_non_HV$Employee_growth_6Months,crmdata_HV$Employee_growth_6Months, mu = 0, var.equal=FALSE) 
#In all but the first t-test we reject the null. Thus we can report that the difference in number of employees is statistically.

sd(crmdata_HV$Employee_count)
sd(crmdata_non_HV$Employee_count)
sd(crmdata_HV$Founded)
sd(crmdata_non_HV$Founded)
sd(crmdata_HV$Employee_growth_6Months)
sd(crmdata_non_HV$Employee_growth_6Months)
```

Results-
Two samples t-test

The means were compared for the number of employees in "High Value" accounts and "Non-High Value" accounts. As predicted, the employees in "High Value" accounts (M = 12569.48, SD=54912.15, N=170) did not have the same mean as "Non-High Value" accounts ( M = 2674.381, SD=15080.76, N= 412), t(169.61) = 2.31, p<.05. The evidence suggests rejection of the null in favor of a Ha. The 95% confidence interval for the difference of the true means is 1456.25 to 18333.95. Thus, the evidence suggests that "High Value" accounts tend to have more employees.  

Given the lack of statistical significance amongst the results for the other two features, I'll ignore making any inferences. 
